---
action: install
module: collectd

common_package_list:
  - curl
  - lsof
  - mc
  - nano
  - tar
  - unzip
  - vim
  - zip

selinux_package_list:
  - policycoreutils
  - selinux-basics 
  - selinux-utils
    #- libselinux-python3


collectd_package_list:
  - collectd
  #- collectd-core
  #- collectd-utils
  - libmicrohttpd12
  - libprotobuf-c1

config_prometheus_port: 9103
config_network_port: 25826
config_network_host: localhost


config_prometheus_collected_modules:
  - df
  - processes
  - protocols
  - swap
  - tcpconns
  - uptime
  - users
  - vmem

config_collectd_folder: '/etc/collectd'
config_collectd_plugin_folder: '/etc/collectd/collectd.conf.d'


config_collectd_template: 'collectd.conf.j2'  
config_collectd: 'collectd.conf'

config_collectd_prometheus_template: 'prometheus.conf.j2'
config_collectd_prometheus: 'prometheus.conf'


config_collectd_network_template: 'network.conf.j2'
config_collectd_network: 'network.conf'

config_collectd_extra_modules_template: 'extra_modules.conf.j2'
config_collectd_extra_modules: 'extra_modules.conf'

