---
- name: Get collectd service status
  systemd:
    name: 'collectd'
  register: collectd_status

- name: Display collectd service status
  debug:
    var: collectd_status.status.ActiveState

- name: Check collected metrix
  shell: 'curl http://localhost:9103'
  register: curl_result
  when: 
    - collectd_status is defined
    - collectd_status.status.ActiveState == "active"

- name: Print result
  debug:
    var: curl_result
  when: 
    - collectd_status is defined
    - collectd_status.status.ActiveState == "active"
