---
- include_tasks: install_collectd.yml
  tags: collectd_install
- include_tasks: configure_collectd.yml
  tags: collectd_install
- include_tasks: check_collectd.yml
  tags: 
    - collectd_check
    - collectd_install
- include_tasks: remove_collectd.yml
  tags: collectd_remove 
