---
- include_tasks: install_collectd.yml
  when:
    - action == 'install'
      #tags: collectd_install
- include_tasks: configure_collectd.yml
  when:
    - action == 'install'
      #tags: collectd_install
- include_tasks: check_collectd.yml
  when:
    - action == 'check'
  #tags: 
  #  - collectd_check
  #  - collectd_install
- include_tasks: remove_collectd.yml
  when:
    - action == 'remove' 

  #tags: collectd_remove 
