---
- name: Stop collectd
  service:
    name: collectd #collectd.service
    state: stopped
    enabled: no
  

- name: Remove collectd and plugins from host
  package:
    name: '{{collectd_package_list}}'
    state: absent
  
- name: Remove collectd config files
  file:
    state: absent
    path: '{{config_collectd_folder}}'

