---
- name: Print Network Interfaces
  hosts: all #managed_nodes
  connection: local
  gather_facts: yes
  gather_subset: 
    - network
    - virtual
  
  tasks:
    - name: Print Network Interfaces
      debug: 
        #  msg: '{{ item }}'
        #loop: '{{ ansible_interfaces }} '
        msg: "{% for item in ansible_interfaces %}{{ item + '\n'}}{% endfor %}"
      
    - name: Print via Setup module
      setup:
        gather_subset:
          - '!all'
          - 'network'
          - 'virtual'
      register: setup_result

    - name: Print result
      debug:
        var: setup_result #.stdout_lines
          #msg: "{{item}}"
          #with_items: 
          #  - "{{setup_result}}"

# Display only facts about certain interfaces.
# ansible all -m ansible.builtin.setup -a 'filter=ansible_eth[0-2]'

# Restrict additional gathered facts to network and virtual (includes default minimum facts)
# ansible all -m ansible.builtin.setup -a 'gather_subset=network,virtual'
