---
- name: Install Required Packages on managed_nodes
  hosts: managed_nodes
  become: yes
  gather_facts: no

  roles:
    - role: common
      tags: one

  
- name: Install and configure collectd service on managed_nodes
  #hosts: managed_nodes
  hosts: control
  connection: local  
  become: yes
  gather_facts: no

  roles:
    - role: collectd
      tags: two
