---
- name: Install Required Packages on managed_nodes
  hosts: managed_nodes
  become: yes
  gather_facts: no
    #tags: common

  roles:
    - role: common
      tags: common

  
- name: Install and configure collectd service on managed_nodes
  #hosts: managed_nodes
  hosts: control
  connection: local  
  become: yes
  gather_facts: no
    #tags: collectd_install

  roles:
    - role: collectd
      tags: collectd_install

- name: Check collectd metrix
  hosts: control
  connection: local
  become: yes
  gather_facts: no
    #tags: collectd_check

  roles:
    - role: collectd
      tags: collectd_check
      

- name: Remove collectd
  hosts: control
  connection: local
  become: yes
  gather_facts: no
    #tags: collectd_remove

  roles:
    - role: collectd
      tags: collectd_remove  
