---
- name: Install Required Packages on managed_nodes
  hosts: managed_nodes
  become: yes
  gather_facts: no

  roles:
    - role: common
      tags: common
      when: 
        - module == 'common'

  
- name: Install and configure collectd service on managed_nodes
  hosts: managed_nodes
  #hosts: control
  #connection: local  
  become: yes
  gather_facts: no

  roles:
    - role: collectd
      when: 
        - module == 'collectd'
        - action == 'install'

- name: Check collectd metrix
  hosts: managed_nodes
  #hosts: control
  #connection: local
  become: yes
  gather_facts: no

  roles:
    - role: collectd
      when: 
        - module == 'collectd'
        - action == 'check'
      

- name: Remove collectd
  hosts: managed_nodes
  #hosts: control
  #connection: local
  become: yes
  gather_facts: no

  roles:
    - role: collectd
      when: 
        - module == 'collectd'
        - action == 'remove'
